name: 'Java GitHub Actions DEMO'
branding:
  icon: activity
  color: purple
description:
  'Executes an action using java code'
author: 'Mustapha Belmokhtar'
inputs:
  java-class:
    description: "Main class"
    required: true
  test:
    description: 'test input'
    required: false
    default: "000000"
  flag:
    description: 'boolean flag'
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Setup inputs
      id: setup-inputs
      run: |
        echo "__inputs<<EOF" >> $GITHUB_OUTPUT
        echo "$__INPUTS_AS_JSON" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
      env:
        __INPUTS_AS_JSON: "${{ toJSON(inputs) }}"
      shell: bash
    - name: Execute java code
      run: |
        VERSION=1.0.0 # todo unify this
        ./mvnw clean install -Drevision=$VERSION&>/dev/null
        java -jar target/java-github-actions-demo-$VERSION.jar
      shell: bash
      env:
        __INPUTS: ${{ steps.setup-inputs.outputs.__inputs }}
        __MAIN_CLASS: ${{ inputs.java-class }}