name: 'Java GitHub Actions'
branding:
  icon: activity
  color: purple
description:
  'Executes an action using java code'
author: 'Mustapha Belmokhtar'
inputs:
  java-class:
    description: "Main class"
    required: true
  test :
    description: 'test input'
    required: false
    default: "000000"

runs:
  using: "composite"
  steps:
    - name: Setup inputs
      run: |
        echo "__inputs<<EOF" >> $GITHUB_ENV
        echo "$__INPUTS_AS_JSON" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      env:
        __INPUTS_AS_JSON: "${{ toJSON(inputs) }}"
      shell: bash
    - name: Execute java code
      run: |
        java -jar java-github-actions-1.0.0-SNAPSHOT.jar
      shell: bash
      env:
        __MAIN_CLASS: ${{ inputs.java-class }}