name: Test

on:
  workflow_dispatch:
    inputs:
      aaaaa:
        required: true
        description: aaaa
        type: string
permissions:
  contents: read

jobs:
  test-job:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install Java
        uses: actions/setup-java@v6
        with:
          java-version: 25
          distribution: 'temurin'
      - name: Uses the java action
        uses: ./test-action
        with:
          test: '000001'
          java-class: src/main/java/test/main/MainTest.java
          aaaa: ${{ inputs.aaaaa }}